version: '3.7'

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myfolder/src
    ports:
      - 3000:3000
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Seoul
      # 혜인님께서 알려주신 TZ Setting. 천사가 따로없는것.

  my-database:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'mydocker04'
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: Asia/Seoul
      # 혜인님께서 알려주신 TZ Setting. 천사가 따로없는것.

    ports:
      - 3306:3306
