steps:
  # 1단계 => docker-compose -f docker-compose.prod.yaml build
  - name: docker/compose:1.29.0
    args:
      - -f
      - class/deploy-with-docker/backend/docker-compose.prod.yaml
      - build

  # 2단계 => docker-compose -f docker-compose.prod.yaml push
  - name: docker/compose:1.29.0
    args:
      - -f
      - class/deploy-with-docker/backend/docker-compose.prod.yaml
      - push

  # 3단계 => kubectl set image deployment/[작업부하] [이미지이름]=[docker.compose.prod.yaml image 이름:version]
  #      => kubectl set image deployment/mybackend04-nestjs mybackend04-nestjs-sha256-1=asia.gcr.io/codecamp-backend04/mybackend04-nestjs:1.6
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/mybackend04-nestjs
      - mybackend04-nestjs-sha256-1=asia.gcr.io/codecamp-backend04/mybackend04-nestjs:1.9
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=mybackend04-cluster-1
