export class CashService {
    checkValue = () => {
        console.log("현금이 있는지 검증합니다. 너 돈 있니?");
        // 1. 가진 돈 검증하는 코드 (대략 10줄 정도)
        // ...
        // ...
        // ...
        // ...
        // ...
    }
}