export class ProductService{
    checkSoldOut = () => {
        console.log("판매가 완료되었는지 검증합니다.")
        // 1. 판매 여부 검증하는 코드 (대략 10줄 정도)
        // ...
        // ...
        // ...
        // ...
        // ...
    }
}