version: '3.7'

services:
  miniproject-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: # local index : docker index
      - ./index.js:/miniproject/index.js
      - ./phone.js:/miniproject/phone.js
      - ./models/:/miniproject/models/
      - ./swagger/:/miniproject/swagger/
      - ./controllers/:/miniproject/controllers/
    ports:
      - 3000:3000 #local에서 postman으로 실험하기 위함


  miniproject-database:
    image: mongo:5
    ports:
      - 27017:27017 #local에서 mongoDB Compass로 확인하기 위함